name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Nightly run at midnight

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest flake8 cryptography

      - name: Run flake8 (Python linting)
        run: flake8 flasK_app.py encrypt_client.py

      - name: Run pytest (Python tests)
        run: pytest --disable-warnings

  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Node.js tests
        run: |
          echo "No tests configured for Node.js. Add your tests here."

  notify:
    runs-on: ubuntu-latest
    needs: [test-python, test-node]
    steps:
      - name: Notify on success/failure
        if: ${{ always() }}
        run: |
          echo "Workflow completed. Check the details for success or failure."
